<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>as400menu</AssemblyName>
    <RootNamespace>Ipc.Console</RootNamespace>
    <StartupObject>Ipc.Console.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ipc.Session\Ipc.Session.csproj" />
    <ProjectReference Include="..\Ipc.Core\Ipc.Core.csproj" />
    <ProjectReference Include="..\Ipc.Services\Ipc.Services.csproj" />
    <ProjectReference Include="..\Ipc.Terminal\Ipc.Terminal.csproj" />
    <ProjectReference Include="..\Ipc.Cl\Ipc.Cl.csproj" />
    <ProjectReference Include="..\Ipc.Db\Ipc.Db.csproj" />
    <ProjectReference Include="..\Ipc.Rpg\Ipc.Rpg.csproj" />
  </ItemGroup>
</Project>
