<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ipc.Cl</AssemblyName>
    <RootNamespace>Ipc.Cl</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Compatibility/catalog.json" />
    <ProjectReference Include="..\Ipc.Core\Ipc.Core.csproj" />
  </ItemGroup>
</Project>
