#!/usr/bin/env python3
"""Render the tracked requirement inventory and observed command/opcode surfaces.

No PLAN.md dependency: local planning files are intentionally Git-ignored.
--check detects stale generated documentation and broken evidence paths in CI.
Observed parser/handler entries are partial implementation evidence, never parity.
"""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def render():
    rows = json.loads((ROOT / "docs/compatibility-matrix.json").read_text())["requirements"]
    ids = [row["id"] for row in rows]
    if len(set(ids)) != len(ids):
        raise ValueError("Duplicate requirement IDs")
    if {r["source"].split()[-1] for r in rows if r["id"].startswith("WP")} != {f"WP{i}" for i in range(23)}:
        raise ValueError("Inventory must cover WP0 through WP22")
    if {r["id"] for r in rows if r["id"].startswith("G")} != {f"G{i:02}" for i in range(1, 14)}:
        raise ValueError("Inventory must cover all thirteen PLAN2 gaps")
    for row in rows:
        if row["status"] not in {"supported", "partial", "planned", "excluded"}:
            raise ValueError(f"Invalid status: {row['id']}")
        for key in ("implementation", "tests", "documentation"):
            for path in row[key]:
                if not (ROOT / path).exists():
                    raise ValueError(f"Missing {key} path for {row['id']}: {path}")
        if row["status"] == "supported" and not (row["tests"] and row["evidence"]):
            raise ValueError(f"Supported requirement lacks evidence: {row['id']}")

    lines = ["# Compatibility matrix", "",
             "Generated by `python3 tools/compatibility-report.py` from the tracked JSON inventory",
             "and current source. Status is deliberately conservative: parser recognition or an",
             "owning test file does not prove the complete requirement. Edit the JSON evidence",
             "when closing requirements, then regenerate. Local PLAN.md/PLAN2.md are not needed.", "",
             "Supported = accepted documented behavior; partial = some owning implementation;",
             "planned = no accepted implementation; excluded = explicit recorded scope decision.", "",
             "[Release scope and decisions](release-scope.md) · [Build baseline](build-baseline.md)", "",
             "## Requirements", "",
             "| ID | Status | Requirement | Implementation / tests | Evidence |",
             "|---|---|---|---|---|"]
    for row in rows:
        links = [f"[{p}](../{p})" for p in row["implementation"] + row["tests"]]
        requirement = row["requirement"].replace("|", "\\|")
        evidence = row["evidence"].replace("|", "\\|")
        lines.append(f"| {row['id']} | {row['status']} | {requirement} | {'; '.join(links) or '—'} | {evidence} |")
    lines += ["", "## Observed console command registrations", "",
              "These handlers have incomplete metadata/security/runtime integration. All remain",
              "partial until their full C07 acceptance evidence is recorded.", "",
              "| Name | Handler | Observation |", "|---|---|---|"]
    source = "\n".join(path.read_text() for path in sorted((ROOT / "src/Ipc.Session/Controllers").glob("*.cs")))
    for name, handler in re.findall(r'_catalog.Register\("([A-Z0-9]+)", (\w+)\)', source):
        note = "Placeholder: fixed empty queue" if handler == "ExecuteNoMessages" else "Partial"
        if name == "ADDSRCPFM":
            note = "iSeriesPC source-workbench extension"
        if name == "DSPMENU":
            note = "iSeriesPC alias for GO"
        lines.append(f"| `{name}` | `{handler}` | {note} |")
    catalog = json.loads((ROOT / "src/Ipc.Cl/Compatibility/catalog.json").read_text())
    entries = catalog["entries"]
    names = [(e["kind"], e["name"].upper()) for e in entries]
    if len(set(names)) != len(names):
        raise ValueError("Duplicate catalog names")
    commands = {e["name"]: e for e in entries if e["kind"] == "command"}
    for alias, target in catalog["aliases"].items():
        if alias in commands or target not in commands:
            raise ValueError(f"Invalid alias: {alias}")
    registered = re.findall(r'_catalog.Register\("([A-Z0-9]+)", (\w+)\)', source)
    for name, _ in registered:
        if name not in commands or "keywords" not in commands[name]:
            raise ValueError(f"Registered command has no input contract: {name}")
    lines += ["", "## Command and API release catalog", "",
              "Names and corrections are normalized against the primary references linked below.",
              "See [compatibility contracts](compatibility-contracts.md) for exact scope and diagnostics.",
              "Planned APIs have no executable ABI yet. Partial commands still need C07 acceptance.", "",
              "| Kind | Name | Origin | Status | Current accepted keywords | Requirement | Reference |",
              "|---|---|---|---|---|---|---|"]
    for e in entries:
        if e["status"] not in {"supported", "partial", "planned", "excluded"}:
            raise ValueError(f"Invalid catalog status: {e['name']}")
        if any(r not in ids for r in e["requirements"]):
            raise ValueError(f"Unknown requirement: {e['name']}")
        ref = f"[IBM]({catalog['references'][e['source']]})" if e['source'] else "Application contract"
        keywords = ", ".join(e.get("keywords", [])) or "—"
        lines.append(f"| {e['kind']} | `{e['name']}` | {e['origin']} | {e['status']} | {keywords} | {', '.join(e['requirements'])} | {ref} |")
    for title, key in [("Accepted legacy aliases", "aliases"), ("Corrected provisional spellings (not aliases)", "corrections"), ("Rejected planning placeholders", "rejectedPlaceholders")]:
        lines += ["", f"### {title}", "", "| Old spelling | Disposition |", "|---|---|"]
        for old, new in catalog[key].items():
            lines.append(f"| `{old}` | {new} |")
    lines += ["", "## Observed RPG opcode parser mappings", "",
              "Recognition is not execution/semantic acceptance. Fixed and free forms can differ.", "",
              "| Spelling | IR opcode |", "|---|---|"]
    source = (ROOT / "src/Ipc.Rpg/Parsing/RpgCompiler.cs").read_text()
    for name, opcode in sorted(set(re.findall(r'"([A-Z-]+)" => RpgOpcode\.(\w+)', source))):
        lines.append(f"| `{name}` | `{opcode}` |")
    lines += ["", "See [RPG specification](rpg-spec.md) and [DDS specification](dds-schema.md) for",
              "current subset details. [Display DDS](display-files.md) has a strict compiler and panel runtime.",
              "[UIM help](shared-help.md) and [command definitions](command-definitions.md) are implemented.",
              "API host, printer DDS, logical-file DDS, and the",
              "complete typed command parameter catalog remain planned. Current PF DDS recognizes",
              "A/S/P/B/F/L/D/T/Z fields and VARLEN/ALWNULL/CCSID/TEXT/DESC keywords; strict rejection",
              "of every unsupported keyword and independent record-codec fixtures remain open.", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = render()
    target = ROOT / "docs/compatibility-matrix.md"
    if args.check:
        if not target.exists() or target.read_text() != output:
            parser.exit(1, "Compatibility report is stale; run python3 tools/compatibility-report.py\n")
    else:
        target.write_text(output)
    print("Compatibility report validated." if args.check else "Compatibility report updated.")


if __name__ == "__main__":
    main()
